apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
    release: kube-prometheus-stack
  name: kube-pod-not-ready
spec:
  groups:
  - name: custom-prometheus-rules
    rules:
    - alert: KubernetesPodUnhealthy
      expr: sum(kube_pod_container_status_restarts_total) by (pod, namespace) > 5
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod restart count is high"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted {{ $value }} times in the last minute."
    - alert: MaxPodRestarts
      expr: sum(kube_pod_container_status_restarts_total) by (pod) > 5
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "Pod restart count is high"
        description: "Pod {{ $labels.pod }} has restarted {{ $value }} times in the last 10 minutes."
    - alert: KubernetesPodNotHealthy
      expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: Kubernetes Pod not healthy (instance {{ $labels.instance }})
        description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-running state for longer than 15 minutes.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"