{
 "title": "818N",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Health Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1 - (sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Health Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "1 - (sum(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) / sum(machine_cpu_cores))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Health Node Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\", status=\"true\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod-Level Metrics Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) by (pod)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes) by (pod)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod-Level Metrics Failed Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"}) by (pod)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod-Level Metrics Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total[5m])) by (pod)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Details # Per Node CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[1h])) by (instance) / \r\nsum(node_cpu_seconds_total) by (instance) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Details # Node Disk I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[1h]) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Details Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Details Node Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes - node_filesystem_free_bytes) by (node)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Details Node Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\", status=\"true\"})\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\", status=\"false\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service-Level Metrics Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_sum[5m])) by (verb) / sum(rate(apiserver_request_duration_seconds_count[5m])) by (verb)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service-Level Metrics Average Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_request_duration_seconds_sum[5m])) by (service) / sum(rate(rest_client_request_duration_seconds_count[5m])) by (service)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network and Storage Monitoring # Network Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[1h])) by (pod, namespace)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service-Level Metrics Monitor Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code=~\"5..\"}[5m])) by (verb) / sum(rate(apiserver_request_total[5m])) by (verb)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network and Storage Monitoring # Storage I/O Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total[1h]) \r\n\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_disk_writes_completed_total[1h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network and Storage Monitoring # Network Bytes Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[1h])) by (pod, namespace)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network and Storage Persistent Volume Metric Collection Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum(rate(kubelet_volume_metric_collection_duration_seconds_sum[5m])) / sum(rate(kubelet_volume_metric_collection_duration_seconds_count[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}